variables:
  GIT_STRATEGY: none

deploy:
  stage: deploy
  script:
    - cd /home/ict/www/skip-project/skip-api
    - git pull origin main
    - cat $env > .env
    - docker-compose build skip-api
    - docker-compose up -d skip-api
  tags:
    - eschool